import { EventWithTickets } from '@/types/event';

// Helper function to generate dates
const getDateOffset = (daysFromNow: number) => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  return date.toISOString();
};

export const mockEvents: EventWithTickets[] = [
  // Music Events
  {
    id: '1',
    event_key: 'jazz-night-vega',
    title: 'Jazz Night at Vega',
    description: 'Experience an unforgettable evening of live jazz music featuring renowned Danish and international artists. The concert includes performances of classic jazz standards and contemporary compositions.',
    category: 'music',
    venue: 'Vega',
    city: 'Copenhagen',
    price: 280,
    original_price: 350,
    event_date: getDateOffset(2),
    takedown_time: getDateOffset(2),
    image_url: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 45 }],
    embedding: null,
  },
  {
    id: '2',
    event_key: 'rock-concert-kb-hallen',
    title: 'Rock Concert at KB Hallen',
    description: 'A massive rock concert featuring some of the biggest names in Scandinavian rock. High-energy performances and an electric atmosphere guaranteed.',
    category: 'music',
    venue: 'KB Hallen',
    city: 'Copenhagen',
    price: 420,
    original_price: 550,
    event_date: getDateOffset(5),
    takedown_time: getDateOffset(5),
    image_url: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
    source_type: 'external',
    source_platform: 'eventbrite',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://eventbrite.com/rock-concert',
    external_booking_url: 'https://eventbrite.com/rock-concert',
    price_on_request: false,
    event_tickets: [{ tickets_left: 120 }],
    embedding: null,
  },
  {
    id: '3',
    event_key: 'classical-tivoli',
    title: 'Classical Music Evening at Tivoli',
    description: 'Enjoy a magical evening of classical music in the beautiful setting of Tivoli Gardens. The Copenhagen Philharmonic Orchestra performs masterpieces by Mozart, Beethoven, and Tchaikovsky.',
    category: 'music',
    venue: 'Tivoli Gardens',
    city: 'Copenhagen',
    price: 320,
    original_price: 400,
    event_date: getDateOffset(7),
    takedown_time: getDateOffset(7),
    image_url: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 200 }],
    embedding: null,
  },
  {
    id: '4',
    event_key: 'electronic-rust',
    title: 'Electronic Dance Night at Rust',
    description: 'Dance the night away to the beats of top electronic music DJs. Featuring house, techno, and progressive electronic music.',
    category: 'nightlife',
    venue: 'Rust',
    city: 'Copenhagen',
    price: 150,
    original_price: 200,
    event_date: getDateOffset(1),
    takedown_time: getDateOffset(1),
    image_url: 'https://images.unsplash.com/photo-1571266028243-d220e0cf8e57?w=800',
    source_type: 'external',
    source_platform: 'billetto',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://billetto.com/electronic-night',
    external_booking_url: 'https://billetto.com/electronic-night',
    price_on_request: false,
    event_tickets: [{ tickets_left: 80 }],
    embedding: null,
  },
  
  // Culture Events
  {
    id: '5',
    event_key: 'art-exhibition-louisiana',
    title: 'Modern Art Exhibition at Louisiana Museum',
    description: 'Explore contemporary art from Nordic and international artists. The exhibition features paintings, sculptures, and multimedia installations.',
    category: 'culture',
    venue: 'Louisiana Museum of Modern Art',
    city: 'Humlebæk',
    price: 145,
    original_price: null,
    event_date: getDateOffset(3),
    takedown_time: getDateOffset(30),
    image_url: 'https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800',
    source_type: 'external',
    source_platform: 'getyourguide',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://getyourguide.com/louisiana',
    external_booking_url: 'https://getyourguide.com/louisiana',
    price_on_request: false,
    event_tickets: [{ tickets_left: 300 }],
    embedding: null,
  },
  {
    id: '6',
    event_key: 'theater-royal-danish',
    title: 'Shakespeare Play at Royal Danish Theatre',
    description: 'A captivating performance of Hamlet by the Royal Danish Theatre company. Experience classic theatre in a historic venue.',
    category: 'culture',
    venue: 'Royal Danish Theatre',
    city: 'Copenhagen',
    price: 280,
    original_price: 350,
    event_date: getDateOffset(8),
    takedown_time: getDateOffset(8),
    image_url: 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 60 }],
    embedding: null,
  },
  {
    id: '7',
    event_key: 'opera-copenhagen',
    title: 'Opera Night at Copenhagen Opera House',
    description: 'An evening of beautiful opera featuring La Traviata. World-class singers and orchestra in one of Europe\'s most modern opera houses.',
    category: 'culture',
    venue: 'Copenhagen Opera House',
    city: 'Copenhagen',
    price: 450,
    original_price: 600,
    event_date: getDateOffset(12),
    takedown_time: getDateOffset(12),
    image_url: 'https://images.unsplash.com/photo-1580809361436-42a7ec204889?w=800',
    source_type: 'external',
    source_platform: 'ticketmaster',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://ticketmaster.com/opera',
    external_booking_url: 'https://ticketmaster.com/opera',
    price_on_request: false,
    event_tickets: [{ tickets_left: 150 }],
    embedding: null,
  },
  
  // Food & Dining Events
  {
    id: '8',
    event_key: 'wine-tasting-tivoli',
    title: 'Wine Tasting Experience at Tivoli',
    description: 'Sample exquisite wines from around the world. Learn about wine pairing from expert sommeliers in the beautiful Tivoli Gardens setting.',
    category: 'food',
    venue: 'Tivoli Gardens',
    city: 'Copenhagen',
    price: 395,
    original_price: 495,
    event_date: getDateOffset(4),
    takedown_time: getDateOffset(4),
    image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 30 }],
    embedding: null,
  },
  {
    id: '9',
    event_key: 'food-festival-refshaleoen',
    title: 'Street Food Festival at Reffen',
    description: 'Enjoy diverse street food from over 30 vendors. International cuisine, craft beer, and live music in Copenhagen\'s hottest food destination.',
    category: 'food',
    venue: 'Reffen',
    city: 'Copenhagen',
    price: 0,
    original_price: null,
    event_date: getDateOffset(6),
    takedown_time: getDateOffset(6),
    image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
    source_type: 'external',
    source_platform: 'eventbrite',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://eventbrite.com/food-festival',
    external_booking_url: 'https://eventbrite.com/food-festival',
    price_on_request: false,
    event_tickets: [{ tickets_left: 500 }],
    embedding: null,
  },
  {
    id: '10',
    event_key: 'cooking-class-noma',
    title: 'Nordic Cooking Class with Noma Chef',
    description: 'Learn to cook authentic Nordic cuisine from a former Noma chef. Hands-on class includes ingredients and a full meal.',
    category: 'food',
    venue: 'Culinary Academy',
    city: 'Copenhagen',
    price: 850,
    original_price: 1050,
    event_date: getDateOffset(10),
    takedown_time: getDateOffset(10),
    image_url: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 12 }],
    embedding: null,
  },
  
  // Fitness & Wellness Events
  {
    id: '11',
    event_key: 'yoga-sunrise-amager',
    title: 'Sunrise Yoga at Amager Beach',
    description: 'Start your day with energizing yoga on the beach. Suitable for all levels. Includes meditation and breathing exercises.',
    category: 'fitness',
    venue: 'Amager Beach',
    city: 'Copenhagen',
    price: 120,
    original_price: 150,
    event_date: getDateOffset(1),
    takedown_time: getDateOffset(1),
    image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 25 }],
    embedding: null,
  },
  {
    id: '12',
    event_key: 'crossfit-challenge',
    title: 'CrossFit Challenge Copenhagen',
    description: 'Test your fitness in this intense CrossFit competition. Categories for beginners and advanced athletes. Prizes for winners.',
    category: 'fitness',
    venue: 'CrossFit Nørrebro',
    city: 'Copenhagen',
    price: 200,
    original_price: 250,
    event_date: getDateOffset(14),
    takedown_time: getDateOffset(14),
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800',
    source_type: 'external',
    source_platform: 'eventbrite',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://eventbrite.com/crossfit',
    external_booking_url: 'https://eventbrite.com/crossfit',
    price_on_request: false,
    event_tickets: [{ tickets_left: 100 }],
    embedding: null,
  },
  {
    id: '13',
    event_key: 'pilates-workshop',
    title: 'Pilates Workshop for Beginners',
    description: 'Learn the fundamentals of Pilates in this comprehensive workshop. Focus on core strength, flexibility, and proper form.',
    category: 'fitness',
    venue: 'Fitness World',
    city: 'Copenhagen',
    price: 180,
    original_price: 220,
    event_date: getDateOffset(5),
    takedown_time: getDateOffset(5),
    image_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 20 }],
    embedding: null,
  },
  
  // Sports Events
  {
    id: '14',
    event_key: 'football-fck-brondby',
    title: 'FC Copenhagen vs Brøndby Derby',
    description: 'The biggest football rivalry in Denmark! Watch FC Copenhagen take on Brøndby IF in this thrilling derby match.',
    category: 'sports',
    venue: 'Parken Stadium',
    city: 'Copenhagen',
    price: 320,
    original_price: 400,
    event_date: getDateOffset(9),
    takedown_time: getDateOffset(9),
    image_url: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800',
    source_type: 'external',
    source_platform: 'ticketmaster',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://ticketmaster.com/fck',
    external_booking_url: 'https://ticketmaster.com/fck',
    price_on_request: false,
    event_tickets: [{ tickets_left: 500 }],
    embedding: null,
  },
  {
    id: '15',
    event_key: 'handball-match',
    title: 'Danish Handball League Match',
    description: 'Experience the excitement of top-level handball. Fast-paced action and incredible athleticism.',
    category: 'sports',
    venue: 'Frederiksberg Hallerne',
    city: 'Copenhagen',
    price: 140,
    original_price: 180,
    event_date: getDateOffset(6),
    takedown_time: getDateOffset(6),
    image_url: 'https://images.unsplash.com/photo-1594977992893-f047c1a3f7c6?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 200 }],
    embedding: null,
  },
  
  // Business & Networking
  {
    id: '16',
    event_key: 'startup-networking',
    title: 'Startup Networking Night',
    description: 'Connect with entrepreneurs, investors, and innovators in Copenhagen\'s startup scene. Includes presentations and networking sessions.',
    category: 'business',
    venue: 'Copenhagen Startup Hub',
    city: 'Copenhagen',
    price: 150,
    original_price: 200,
    event_date: getDateOffset(7),
    takedown_time: getDateOffset(7),
    image_url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 80 }],
    embedding: null,
  },
  {
    id: '17',
    event_key: 'tech-conference',
    title: 'Nordic Tech Conference 2024',
    description: 'Two-day conference featuring talks from tech leaders, workshops, and networking opportunities. Topics include AI, blockchain, and sustainability.',
    category: 'business',
    venue: 'Bella Center',
    city: 'Copenhagen',
    price: 1200,
    original_price: 1500,
    event_date: getDateOffset(21),
    takedown_time: getDateOffset(21),
    image_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
    source_type: 'external',
    source_platform: 'eventbrite',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://eventbrite.com/tech-conf',
    external_booking_url: 'https://eventbrite.com/tech-conf',
    price_on_request: false,
    event_tickets: [{ tickets_left: 300 }],
    embedding: null,
  },
  
  // Entertainment
  {
    id: '18',
    event_key: 'comedy-show',
    title: 'Stand-Up Comedy Night',
    description: 'Laugh out loud with Denmark\'s funniest comedians. An evening of hilarious stand-up comedy in English and Danish.',
    category: 'entertainment',
    venue: 'The Comedy Zoo',
    city: 'Copenhagen',
    price: 180,
    original_price: 220,
    event_date: getDateOffset(3),
    takedown_time: getDateOffset(3),
    image_url: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 120 }],
    embedding: null,
  },
  {
    id: '19',
    event_key: 'magic-show',
    title: 'Magic & Illusion Show',
    description: 'Be amazed by world-class magicians performing mind-bending illusions and magic tricks. Perfect for families.',
    category: 'entertainment',
    venue: 'Glassalen',
    city: 'Copenhagen',
    price: 250,
    original_price: 300,
    event_date: getDateOffset(11),
    takedown_time: getDateOffset(11),
    image_url: 'https://images.unsplash.com/photo-1500099817043-86d46000d58f?w=800',
    source_type: 'external',
    source_platform: 'ticketmaster',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://ticketmaster.com/magic',
    external_booking_url: 'https://ticketmaster.com/magic',
    price_on_request: false,
    event_tickets: [{ tickets_left: 200 }],
    embedding: null,
  },
  {
    id: '20',
    event_key: 'trivia-night',
    title: 'Pub Quiz & Trivia Night',
    description: 'Test your knowledge in this fun pub quiz night. Categories include history, pop culture, sports, and more. Prizes for winners!',
    category: 'entertainment',
    venue: 'Mikkeller Bar',
    city: 'Copenhagen',
    price: 80,
    original_price: 100,
    event_date: getDateOffset(2),
    takedown_time: getDateOffset(2),
    image_url: 'https://images.unsplash.com/photo-1531058020387-3be344556be6?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 60 }],
    embedding: null,
  },
  {
    id: '21',
    event_key: 'board-game-night',
    title: 'Board Game Café Night',
    description: 'Join us for a cozy evening of board games. Over 200 games to choose from. Beginners welcome!',
    category: 'entertainment',
    venue: 'Bastard Café',
    city: 'Copenhagen',
    price: 60,
    original_price: null,
    event_date: getDateOffset(1),
    takedown_time: getDateOffset(1),
    image_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 40 }],
    embedding: null,
  },
  
  // Social Events
  {
    id: '22',
    event_key: 'speed-dating',
    title: 'Speed Dating for Young Professionals',
    description: 'Meet singles in Copenhagen in a fun, relaxed environment. Ages 25-35. Includes welcome drink and ice-breaker activities.',
    category: 'social',
    venue: 'Café Norden',
    city: 'Copenhagen',
    price: 200,
    original_price: 250,
    event_date: getDateOffset(8),
    takedown_time: getDateOffset(8),
    image_url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800',
    source_type: 'external',
    source_platform: 'eventbrite',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://eventbrite.com/speed-dating',
    external_booking_url: 'https://eventbrite.com/speed-dating',
    price_on_request: false,
    event_tickets: [{ tickets_left: 30 }],
    embedding: null,
  },
  {
    id: '23',
    event_key: 'language-exchange',
    title: 'International Language Exchange Meetup',
    description: 'Practice languages with native speakers from around the world. Casual atmosphere, all levels welcome. Over 20 languages represented.',
    category: 'social',
    venue: 'Copenhagen Central Library',
    city: 'Copenhagen',
    price: 0,
    original_price: null,
    event_date: getDateOffset(4),
    takedown_time: getDateOffset(4),
    image_url: 'https://images.unsplash.com/photo-1513128034602-7814ccaddd4e?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 100 }],
    embedding: null,
  },
  
  // More Music Events (different genres)
  {
    id: '24',
    event_key: 'indie-folk-concert',
    title: 'Indie Folk Night',
    description: 'Intimate acoustic performances by up-and-coming folk artists. Singer-songwriters and storytellers.',
    category: 'music',
    venue: 'Loppen',
    city: 'Copenhagen',
    price: 120,
    original_price: 150,
    event_date: getDateOffset(6),
    takedown_time: getDateOffset(6),
    image_url: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 80 }],
    embedding: null,
  },
  {
    id: '25',
    event_key: 'reggae-party',
    title: 'Reggae & Dancehall Party',
    description: 'Caribbean vibes in Copenhagen! Dance to reggae, dancehall, and afrobeats. Live DJ and good vibes only.',
    category: 'music',
    venue: 'Jolene',
    city: 'Copenhagen',
    price: 100,
    original_price: 130,
    event_date: getDateOffset(3),
    takedown_time: getDateOffset(3),
    image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    source_type: 'external',
    source_platform: 'billetto',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://billetto.com/reggae',
    external_booking_url: 'https://billetto.com/reggae',
    price_on_request: false,
    event_tickets: [{ tickets_left: 150 }],
    embedding: null,
  },
  {
    id: '26',
    event_key: 'metal-concert',
    title: 'Heavy Metal Night',
    description: 'Headbanging metal concert featuring local and international metal bands. Mosh pit ready!',
    category: 'music',
    venue: 'Pumpehuset',
    city: 'Copenhagen',
    price: 180,
    original_price: 220,
    event_date: getDateOffset(13),
    takedown_time: getDateOffset(13),
    image_url: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 200 }],
    embedding: null,
  },
  {
    id: '27',
    event_key: 'hip-hop-battle',
    title: 'Hip Hop Dance Battle',
    description: 'Watch the best hip hop dancers compete in this high-energy battle. B-boying, popping, locking, and more.',
    category: 'music',
    venue: 'Culture Box',
    city: 'Copenhagen',
    price: 130,
    original_price: 160,
    event_date: getDateOffset(9),
    takedown_time: getDateOffset(9),
    image_url: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=800',
    source_type: 'external',
    source_platform: 'eventbrite',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://eventbrite.com/hiphop',
    external_booking_url: 'https://eventbrite.com/hiphop',
    price_on_request: false,
    event_tickets: [{ tickets_left: 120 }],
    embedding: null,
  },
  
  // More Culture Events
  {
    id: '28',
    event_key: 'photography-exhibition',
    title: 'Contemporary Photography Exhibition',
    description: 'Stunning photography exhibition showcasing work from emerging Nordic photographers. Themes of nature, urban life, and identity.',
    category: 'culture',
    venue: 'Fotografisk Center',
    city: 'Copenhagen',
    price: 80,
    original_price: 100,
    event_date: getDateOffset(5),
    takedown_time: getDateOffset(20),
    image_url: 'https://images.unsplash.com/photo-1531058020387-3be344556be6?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 150 }],
    embedding: null,
  },
  {
    id: '29',
    event_key: 'ballet-performance',
    title: 'Ballet Performance - Swan Lake',
    description: 'Classic ballet performance of Tchaikovsky\'s Swan Lake. Royal Danish Ballet performs this timeless masterpiece.',
    category: 'culture',
    venue: 'Royal Danish Theatre',
    city: 'Copenhagen',
    price: 380,
    original_price: 480,
    event_date: getDateOffset(15),
    takedown_time: getDateOffset(15),
    image_url: 'https://images.unsplash.com/photo-1508807526345-15e9b5f4eaff?w=800',
    source_type: 'external',
    source_platform: 'ticketmaster',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://ticketmaster.com/ballet',
    external_booking_url: 'https://ticketmaster.com/ballet',
    price_on_request: false,
    event_tickets: [{ tickets_left: 100 }],
    embedding: null,
  },
  {
    id: '30',
    event_key: 'poetry-slam',
    title: 'Poetry Slam Championship',
    description: 'Watch talented poets compete in this electrifying poetry slam. Powerful words, raw emotions, and fierce competition.',
    category: 'culture',
    venue: 'Huset',
    city: 'Copenhagen',
    price: 90,
    original_price: 120,
    event_date: getDateOffset(7),
    takedown_time: getDateOffset(7),
    image_url: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 70 }],
    embedding: null,
  },
  
  // Nightlife
  {
    id: '31',
    event_key: 'cocktail-workshop',
    title: 'Mixology & Cocktail Workshop',
    description: 'Learn to make classic and modern cocktails from professional bartenders. Hands-on workshop with tastings.',
    category: 'nightlife',
    venue: 'Ruby',
    city: 'Copenhagen',
    price: 320,
    original_price: 400,
    event_date: getDateOffset(10),
    takedown_time: getDateOffset(10),
    image_url: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 20 }],
    embedding: null,
  },
  {
    id: '32',
    event_key: 'karaoke-night',
    title: 'Karaoke Night at Jailhouse',
    description: 'Sing your heart out at Copenhagen\'s most fun karaoke bar. Private rooms and public stage available.',
    category: 'nightlife',
    venue: 'Jailhouse CPH',
    city: 'Copenhagen',
    price: 50,
    original_price: null,
    event_date: getDateOffset(2),
    takedown_time: getDateOffset(2),
    image_url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 100 }],
    embedding: null,
  },
  {
    id: '33',
    event_key: 'silent-disco',
    title: 'Silent Disco in the Park',
    description: 'Dance to three different DJ channels through wireless headphones. Unique outdoor party experience.',
    category: 'nightlife',
    venue: 'Fælledparken',
    city: 'Copenhagen',
    price: 140,
    original_price: 180,
    event_date: getDateOffset(4),
    takedown_time: getDateOffset(4),
    image_url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800',
    source_type: 'external',
    source_platform: 'billetto',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://billetto.com/silent-disco',
    external_booking_url: 'https://billetto.com/silent-disco',
    price_on_request: false,
    event_tickets: [{ tickets_left: 250 }],
    embedding: null,
  },
  
  // More Fitness
  {
    id: '34',
    event_key: 'spin-class-party',
    title: 'Spin Class Party with DJ',
    description: 'High-energy spin class with live DJ. Burn calories while dancing on the bike. All fitness levels welcome.',
    category: 'fitness',
    venue: 'Revolution Spin',
    city: 'Copenhagen',
    price: 150,
    original_price: 180,
    event_date: getDateOffset(5),
    takedown_time: getDateOffset(5),
    image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 30 }],
    embedding: null,
  },
  {
    id: '35',
    event_key: 'outdoor-bootcamp',
    title: 'Outdoor Bootcamp Training',
    description: 'Intense outdoor fitness bootcamp. Bodyweight exercises, running, and team challenges in beautiful surroundings.',
    category: 'fitness',
    venue: 'Kongens Have',
    city: 'Copenhagen',
    price: 100,
    original_price: 130,
    event_date: getDateOffset(3),
    takedown_time: getDateOffset(3),
    image_url: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=800',
    source_type: 'external',
    source_platform: 'eventbrite',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://eventbrite.com/bootcamp',
    external_booking_url: 'https://eventbrite.com/bootcamp',
    price_on_request: false,
    event_tickets: [{ tickets_left: 40 }],
    embedding: null,
  },
  {
    id: '36',
    event_key: 'meditation-retreat',
    title: 'One-Day Meditation Retreat',
    description: 'Disconnect and recharge with guided meditation, mindfulness practices, and silent reflection. Includes vegetarian lunch.',
    category: 'fitness',
    venue: 'Zenminds Studio',
    city: 'Copenhagen',
    price: 450,
    original_price: 550,
    event_date: getDateOffset(16),
    takedown_time: getDateOffset(16),
    image_url: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 15 }],
    embedding: null,
  },
  
  // More Food
  {
    id: '37',
    event_key: 'chocolate-tasting',
    title: 'Artisan Chocolate Tasting',
    description: 'Indulge in premium chocolates from around the world. Learn about bean-to-bar chocolate making.',
    category: 'food',
    venue: 'Summerbird Chocolaterie',
    city: 'Copenhagen',
    price: 220,
    original_price: 280,
    event_date: getDateOffset(8),
    takedown_time: getDateOffset(8),
    image_url: 'https://images.unsplash.com/photo-1481391243133-f96216dcb5d2?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 25 }],
    embedding: null,
  },
  {
    id: '38',
    event_key: 'sushi-making',
    title: 'Sushi Making Class',
    description: 'Master the art of sushi making with a Japanese chef. Learn to roll maki, nigiri, and sashimi preparation.',
    category: 'food',
    venue: 'Sticks\'n\'Sushi',
    city: 'Copenhagen',
    price: 520,
    original_price: 650,
    event_date: getDateOffset(12),
    takedown_time: getDateOffset(12),
    image_url: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800',
    source_type: 'external',
    source_platform: 'getyourguide',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://getyourguide.com/sushi',
    external_booking_url: 'https://getyourguide.com/sushi',
    price_on_request: false,
    event_tickets: [{ tickets_left: 16 }],
    embedding: null,
  },
  {
    id: '39',
    event_key: 'beer-brewery-tour',
    title: 'Craft Beer Brewery Tour',
    description: 'Tour Copenhagen\'s best craft breweries. Taste 8 different beers and learn about the brewing process.',
    category: 'food',
    venue: 'Mikkeller Brewery',
    city: 'Copenhagen',
    price: 280,
    original_price: 350,
    event_date: getDateOffset(6),
    takedown_time: getDateOffset(6),
    image_url: 'https://images.unsplash.com/photo-1532634993-15f421e42ec0?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 20 }],
    embedding: null,
  },
  
  // More Entertainment
  {
    id: '40',
    event_key: 'escape-room',
    title: 'Escape Room Challenge',
    description: 'Solve puzzles and crack codes to escape in 60 minutes. Multiple themed rooms available. Great for groups!',
    category: 'entertainment',
    venue: 'Escape Copenhagen',
    city: 'Copenhagen',
    price: 250,
    original_price: 300,
    event_date: getDateOffset(4),
    takedown_time: getDateOffset(4),
    image_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 10 }],
    embedding: null,
  },
  {
    id: '41',
    event_key: 'improv-theater',
    title: 'Improv Comedy Show',
    description: 'Unpredictable, hilarious, and completely improvised comedy. Every show is unique and interactive.',
    category: 'entertainment',
    venue: 'Improv Comedy Copenhagen',
    city: 'Copenhagen',
    price: 130,
    original_price: 160,
    event_date: getDateOffset(5),
    takedown_time: getDateOffset(5),
    image_url: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800',
    source_type: 'external',
    source_platform: 'eventbrite',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://eventbrite.com/improv',
    external_booking_url: 'https://eventbrite.com/improv',
    price_on_request: false,
    event_tickets: [{ tickets_left: 60 }],
    embedding: null,
  },
  {
    id: '42',
    event_key: 'gaming-tournament',
    title: 'E-Sports Gaming Tournament',
    description: 'Compete in popular video games or watch the pros. Prizes for winners. Games include CS:GO, FIFA, and League of Legends.',
    category: 'entertainment',
    venue: 'Bastard Café',
    city: 'Copenhagen',
    price: 150,
    original_price: 200,
    event_date: getDateOffset(11),
    takedown_time: getDateOffset(11),
    image_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 50 }],
    embedding: null,
  },
  
  // Additional variety events
  {
    id: '43',
    event_key: 'ghost-tour',
    title: 'Copenhagen Ghost Tour',
    description: 'Explore Copenhagen\'s haunted history on this spooky walking tour. Hear tales of ghosts, murders, and mysteries.',
    category: 'entertainment',
    venue: 'Old Town Copenhagen',
    city: 'Copenhagen',
    price: 180,
    original_price: 220,
    event_date: getDateOffset(7),
    takedown_time: getDateOffset(7),
    image_url: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=800',
    source_type: 'external',
    source_platform: 'getyourguide',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://getyourguide.com/ghost-tour',
    external_booking_url: 'https://getyourguide.com/ghost-tour',
    price_on_request: false,
    event_tickets: [{ tickets_left: 30 }],
    embedding: null,
  },
  {
    id: '44',
    event_key: 'salsa-night',
    title: 'Salsa Dancing Night',
    description: 'Learn salsa dancing or practice your moves. Beginner lesson at 8pm, social dancing from 9pm. Live band!',
    category: 'social',
    venue: 'Sabor Latino',
    city: 'Copenhagen',
    price: 120,
    original_price: 150,
    event_date: getDateOffset(3),
    takedown_time: getDateOffset(3),
    image_url: 'https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 80 }],
    embedding: null,
  },
  {
    id: '45',
    event_key: 'sailing-trip',
    title: 'Sunset Sailing Trip',
    description: 'Sail around Copenhagen harbor at sunset. No sailing experience needed. Includes wine and snacks.',
    category: 'social',
    venue: 'Copenhagen Harbor',
    city: 'Copenhagen',
    price: 390,
    original_price: 480,
    event_date: getDateOffset(5),
    takedown_time: getDateOffset(5),
    image_url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
    source_type: 'external',
    source_platform: 'getyourguide',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://getyourguide.com/sailing',
    external_booking_url: 'https://getyourguide.com/sailing',
    price_on_request: false,
    event_tickets: [{ tickets_left: 12 }],
    embedding: null,
  },
  {
    id: '46',
    event_key: 'painting-class',
    title: 'Paint & Sip Evening',
    description: 'Unleash your creativity while enjoying wine. No experience needed - professional artist guides you step by step.',
    category: 'culture',
    venue: 'Paint Bar Copenhagen',
    city: 'Copenhagen',
    price: 280,
    original_price: 350,
    event_date: getDateOffset(9),
    takedown_time: getDateOffset(9),
    image_url: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 25 }],
    embedding: null,
  },
  {
    id: '47',
    event_key: 'bike-tour',
    title: 'Copenhagen Bike Tour',
    description: 'Explore Copenhagen like a local on this guided bike tour. See all major sights and hidden gems. Bike and helmet included.',
    category: 'social',
    venue: 'City Center',
    city: 'Copenhagen',
    price: 180,
    original_price: 220,
    event_date: getDateOffset(4),
    takedown_time: getDateOffset(4),
    image_url: 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800',
    source_type: 'external',
    source_platform: 'getyourguide',
    booking_mode: 'external_redirect',
    pricing_mode: 'standard',
    affiliate_link: 'https://getyourguide.com/bike-tour',
    external_booking_url: 'https://getyourguide.com/bike-tour',
    price_on_request: false,
    event_tickets: [{ tickets_left: 15 }],
    embedding: null,
  },
  {
    id: '48',
    event_key: 'film-screening',
    title: 'Outdoor Film Screening',
    description: 'Watch a classic film under the stars. Bring a blanket and enjoy free popcorn. This week: Casablanca.',
    category: 'culture',
    venue: 'Dronning Louises Bro',
    city: 'Copenhagen',
    price: 0,
    original_price: null,
    event_date: getDateOffset(6),
    takedown_time: getDateOffset(6),
    image_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 300 }],
    embedding: null,
  },
  {
    id: '49',
    event_key: 'jazz-brunch',
    title: 'Jazz Brunch at Tivoli',
    description: 'Enjoy a delicious brunch buffet with live jazz music. Perfect Sunday activity. Includes unlimited coffee and mimosas.',
    category: 'food',
    venue: 'Tivoli Gardens',
    city: 'Copenhagen',
    price: 420,
    original_price: 520,
    event_date: getDateOffset(10),
    takedown_time: getDateOffset(10),
    image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 40 }],
    embedding: null,
  },
  {
    id: '50',
    event_key: 'astronomy-night',
    title: 'Stargazing Night at Observatory',
    description: 'Look through powerful telescopes and learn about constellations from astronomers. Clear night guaranteed or reschedule.',
    category: 'culture',
    venue: 'Tycho Brahe Planetarium',
    city: 'Copenhagen',
    price: 160,
    original_price: 200,
    event_date: getDateOffset(14),
    takedown_time: getDateOffset(14),
    image_url: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=800',
    source_type: 'native',
    source_platform: null,
    booking_mode: 'spontanique_checkout',
    pricing_mode: 'standard',
    affiliate_link: null,
    external_booking_url: null,
    price_on_request: false,
    event_tickets: [{ tickets_left: 35 }],
    embedding: null,
  },
];
